// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDepartment = "departments"

// Department mapped from table <departments>
type Department struct {
	ID   string  `gorm:"column:id;type:varchar(36);primaryKey" json:"id"`
	Name *string `gorm:"column:name;type:varchar(55)" json:"name"`
}

// TableName Department's table name
func (*Department) TableName() string {
	return TableNameDepartment
}
