// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEmployee = "employees"

// Employee mapped from table <employees>
type Employee struct {
	ID     string  `gorm:"column:id;type:varchar(36);primaryKey" json:"id"`
	UserID *string `gorm:"column:user_id;type:varchar(36);uniqueIndex:uq_user_id,priority:1" json:"user_id"`
	DeptID *string `gorm:"column:dept_id;type:varchar(36);index:FK_dept_id,priority:1" json:"dept_id"`
}

// TableName Employee's table name
func (*Employee) TableName() string {
	return TableNameEmployee
}
