// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID        string  `gorm:"column:id;type:varchar(36);primaryKey" json:"id"`
	Firstname *string `gorm:"column:firstname;type:varchar(55)" json:"firstname"`
	Lastname  *string `gorm:"column:lastname;type:varchar(55)" json:"lastname"`
	Username  *string `gorm:"column:username;type:varchar(55)" json:"username"`
	Userscol  *string `gorm:"column:userscol;type:varchar(45)" json:"userscol"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
